// <auto-generated />
using System;
using API_LocadoraVeiculos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_LocadoraVeiculos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_LocadoraVeiculos.Models.Clientes.ClienteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataNasc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumCnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidadeCnh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("API_LocadoraVeiculos.Models.Locacoes.LocacaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFimPrevista")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFimReal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_up")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updated_up")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Locacoes");
                });

            modelBuilder.Entity("API_LocadoraVeiculos.Models.Pagamentos.PagamentoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data_pagamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocacaoId")
                        .HasColumnType("int");

                    b.Property<int>("MetodoPag")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LocacaoId");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("API_LocadoraVeiculos.Models.Veiculos.CategoriaVeiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCateg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Carros compactos e econômicos",
                            NomeCateg = "Hatch"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Carros com porta-malas grande, ideais para viagens",
                            NomeCateg = "Sedan"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Utilitários esportivos, espaço e conforto",
                            NomeCateg = "SUV"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Veículos para carga e trabalho",
                            NomeCateg = "Picape"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Veículos para transporte de grupos",
                            NomeCateg = "Van"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Alta performance e design arrojado",
                            NomeCateg = "Esportivo"
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Conforto e sofisticação premium",
                            NomeCateg = "Luxo"
                        });
                });

            modelBuilder.Entity("API_LocadoraVeiculos.Models.Veiculos.CorVeiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HexaCor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HexaCor = "#FFFFFF",
                            cor = "Branco"
                        },
                        new
                        {
                            Id = 2,
                            HexaCor = "#000000",
                            cor = "Preto"
                        },
                        new
                        {
                            Id = 3,
                            HexaCor = "#C0C0C0",
                            cor = "Prata"
                        },
                        new
                        {
                            Id = 4,
                            HexaCor = "#FF0000",
                            cor = "Vermelho"
                        },
                        new
                        {
                            Id = 5,
                            HexaCor = "#0000FF",
                            cor = "Azul"
                        },
                        new
                        {
                            Id = 6,
                            HexaCor = "#008000",
                            cor = "Verde"
                        },
                        new
                        {
                            Id = 7,
                            HexaCor = "#FFFF00",
                            cor = "Amarelo"
                        },
                        new
                        {
                            Id = 8,
                            HexaCor = "#808080",
                            cor = "Cinza"
                        },
                        new
                        {
                            Id = 9,
                            HexaCor = "#8B4513",
                            cor = "Marrom"
                        },
                        new
                        {
                            Id = 10,
                            HexaCor = "#F5F5DC",
                            cor = "Bege"
                        });
                });

            modelBuilder.Entity("API_LocadoraVeiculos.Models.Veiculos.VeiculoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoVeiculo")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("CorId")
                        .HasColumnType("int");

                    b.Property<string>("NomeModelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorDiaria")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CorId");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("API_LocadoraVeiculos.Models.Locacoes.LocacaoModel", b =>
                {
                    b.HasOne("API_LocadoraVeiculos.Models.Clientes.ClienteModel", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_LocadoraVeiculos.Models.Veiculos.VeiculoModel", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("API_LocadoraVeiculos.Models.Pagamentos.PagamentoModel", b =>
                {
                    b.HasOne("API_LocadoraVeiculos.Models.Locacoes.LocacaoModel", "Locacao")
                        .WithMany()
                        .HasForeignKey("LocacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locacao");
                });

            modelBuilder.Entity("API_LocadoraVeiculos.Models.Veiculos.VeiculoModel", b =>
                {
                    b.HasOne("API_LocadoraVeiculos.Models.Veiculos.CategoriaVeiculo", "Categoria")
                        .WithMany("Veiculos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_LocadoraVeiculos.Models.Veiculos.CorVeiculo", "Cor")
                        .WithMany("Veiculos")
                        .HasForeignKey("CorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Cor");
                });

            modelBuilder.Entity("API_LocadoraVeiculos.Models.Veiculos.CategoriaVeiculo", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("API_LocadoraVeiculos.Models.Veiculos.CorVeiculo", b =>
                {
                    b.Navigation("Veiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
